/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package modpackDownloader;

import org.junit.jupiter.api.Test;

import modpackDownloader.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        //there are no tests here, move on
        //App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
